# **Aguado, Emmanuel D.**
# **Du, Ellyanna Nicole L.**
# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [1]:
import numpy as np

#### 2. Print the numpy version

In [2]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 1, 8, 9, 10, 11, 12, 13, 14, 15])
print(arr)

[ 1  2  3  4  5  6  1  8  9 10 11 12 13 14 15]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [4]:
import numpy as np
arr = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 0]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15  0]]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [5]:
import numpy as np
arr = np.array([1, 2, 4, 0, 4, 0])
x = np.where(arr != 0)
print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [10]:
import numpy as np
from numpy import random
x = random.rand(4,4,4)
print(x)

[[[0.60999183 0.76402329 0.5248151  0.21246952]
  [0.19695124 0.70104552 0.27097364 0.96372536]
  [0.41870344 0.02652993 0.02903638 0.29268463]
  [0.2351759  0.84163996 0.78159971 0.02881061]]

 [[0.03526655 0.42923286 0.47349123 0.96652921]
  [0.96631651 0.99030441 0.01495987 0.69569341]
  [0.50800552 0.07411083 0.3981094  0.72098264]
  [0.5190927  0.74164639 0.95510278 0.2510282 ]]

 [[0.90095998 0.87064641 0.17885082 0.32322255]
  [0.93299149 0.30381797 0.13716892 0.52301974]
  [0.40178376 0.60726943 0.93825954 0.68287125]
  [0.03170561 0.55072433 0.7133423  0.40667449]]

 [[0.31840648 0.90390798 0.28859671 0.96668623]
  [0.78064587 0.86359179 0.80416195 0.52868132]
  [0.60025599 0.18610951 0.98482441 0.11308222]
  [0.33946869 0.68213111 0.5615875  0.57808231]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [9]:
x = random.rand(15,15)
print(x)

[[0.06113011 0.74770404 0.37941756 0.75812965 0.27095404 0.87553273
  0.72239966 0.29747885 0.22277328 0.14465069 0.60640893 0.21220304
  0.23285672 0.71310298 0.51797229]
 [0.34066664 0.60391379 0.24436255 0.76057017 0.63162505 0.03946859
  0.42454881 0.76890085 0.53195219 0.86473725 0.46190623 0.92741266
  0.41486481 0.48747973 0.48223641]
 [0.90821245 0.74428386 0.76319098 0.17045016 0.49928739 0.23353031
  0.6798072  0.33687901 0.64573843 0.55509242 0.24494142 0.94656444
  0.93297526 0.33139967 0.64039337]
 [0.32834869 0.26342345 0.26804223 0.08499566 0.92819707 0.41462651
  0.75331295 0.34503069 0.88435039 0.04442055 0.65333082 0.59662309
  0.38980068 0.07703848 0.68984067]
 [0.20201311 0.37792457 0.57119305 0.90537146 0.31591823 0.9507068
  0.04212837 0.30058743 0.34634442 0.47305345 0.92829822 0.35268465
  0.71900003 0.27611678 0.51094841]
 [0.99061044 0.20581502 0.87215287 0.51752596 0.51023803 0.28060478
  0.54973616 0.03149363 0.59923634 0.75002491 0.79997043 0.06229145
  0.9

In [11]:
x.min()
x.max()

np.float64(0.990304407652944)

#### 9. Create a random array of size 25 and find the mean value

In [13]:
x = random.randint(100, size=(25))
arr = ([x])
print(arr)
x.mean()

[array([14, 50, 19, 72, 30, 90, 73, 65, 77, 35,  6, 39, 86, 27, 45, 35, 46,
       62, 65, 29, 35, 34, 72, 90, 20])]


np.float64(48.64)

#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [17]:
array1 = np.array([2, 4, 9])
array2 = np.array([1, 14, 6])
print(array1, array2)

[2 4 9] [ 1 14  6]


10.1 What is the result of *a + b*?

In [18]:
print(array1 + array2)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [19]:
print(array1 - array2)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [20]:
print(array1 * array2)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [21]:
print(array1 / array2)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [45]:
arr = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [27]:
print(arr[1, 1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [29]:
arr2 =  arr[1:2]
print(arr2)

[[40 50 60]]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [52]:
print(arr[0:3, 2])

[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [54]:
arr3 = np.array(arr[1:3, 1:3]) 
print(arr3)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [58]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [59]:
arr1 = np.array(arr[1:3, 1:3])
print(arr1)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [62]:
arr2 = np.array(arr[0:1, ::2])
print(arr2)

[[1 3]]


4. Write code to reverse the order of rows in the matrix

In [ ]:
arr3 = np.array(arr[])

5. Write code to extract the last two columns of the matrix.

##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

2. Write code to join arr1 and arr2 into a single 1D array.

3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

5. Write code to join them horizontally (column-wise).

6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.