# **Aguado, Emmanuel D.**
# **Du, Ellyanna Nicole L.**
# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [1]:
import numpy as np

#### 2. Print the numpy version

In [2]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 1, 8, 9, 10, 11, 12, 13, 14, 15])
print(arr)

[ 1  2  3  4  5  6  1  8  9 10 11 12 13 14 15]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [4]:
import numpy as np
arr = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 0]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15  0]]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [5]:
import numpy as np
arr = np.array([1, 2, 4, 0, 4, 0])
x = np.where(arr != 0)
print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [10]:
import numpy as np
from numpy import random

x = random.rand(4,4,4)
print(x)

[[[0.60999183 0.76402329 0.5248151  0.21246952]
  [0.19695124 0.70104552 0.27097364 0.96372536]
  [0.41870344 0.02652993 0.02903638 0.29268463]
  [0.2351759  0.84163996 0.78159971 0.02881061]]

 [[0.03526655 0.42923286 0.47349123 0.96652921]
  [0.96631651 0.99030441 0.01495987 0.69569341]
  [0.50800552 0.07411083 0.3981094  0.72098264]
  [0.5190927  0.74164639 0.95510278 0.2510282 ]]

 [[0.90095998 0.87064641 0.17885082 0.32322255]
  [0.93299149 0.30381797 0.13716892 0.52301974]
  [0.40178376 0.60726943 0.93825954 0.68287125]
  [0.03170561 0.55072433 0.7133423  0.40667449]]

 [[0.31840648 0.90390798 0.28859671 0.96668623]
  [0.78064587 0.86359179 0.80416195 0.52868132]
  [0.60025599 0.18610951 0.98482441 0.11308222]
  [0.33946869 0.68213111 0.5615875  0.57808231]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [108]:
x = random.rand(15,15)
print(x)
min_value = np.min(x)
max_value = np.max(x)
print(min_value)
print(max_value)

[[0.14906549 0.8231083  0.81010751 0.67910017 0.12135904 0.24327319
  0.86059403 0.68174733 0.2102296  0.48141799 0.13713624 0.45838399
  0.63489156 0.60695304 0.65252781]
 [0.54181355 0.36090401 0.13083494 0.83803515 0.98203043 0.83301406
  0.76233009 0.56629229 0.80399745 0.70918894 0.50537124 0.35146732
  0.76559236 0.61878905 0.49556201]
 [0.98799398 0.06120974 0.8289465  0.28469832 0.42270826 0.19705703
  0.83322906 0.2598324  0.69745116 0.28958691 0.29971583 0.72663091
  0.46132464 0.54393387 0.18609391]
 [0.3022775  0.55792469 0.25676489 0.29870084 0.03353804 0.67129907
  0.14433332 0.99133543 0.80292399 0.4872383  0.15164856 0.28148843
  0.66178454 0.15049421 0.26681156]
 [0.85832206 0.48120917 0.41751458 0.90344401 0.25656296 0.22643146
  0.8099836  0.60220769 0.57260527 0.93818206 0.96095582 0.51560685
  0.94961016 0.74479958 0.24619738]
 [0.35959159 0.78134259 0.67462132 0.80400611 0.27503185 0.64221851
  0.94953928 0.25788537 0.23896547 0.69803146 0.25418606 0.99568189
  0.

In [11]:
x.min()
x.max()

np.float64(0.990304407652944)

#### 9. Create a random array of size 25 and find the mean value

In [13]:
x = random.randint(100, size=(25))
arr = ([x])
print(arr)
x.mean()

[array([14, 50, 19, 72, 30, 90, 73, 65, 77, 35,  6, 39, 86, 27, 45, 35, 46,
       62, 65, 29, 35, 34, 72, 90, 20])]


np.float64(48.64)

#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [17]:
array1 = np.array([2, 4, 9])
array2 = np.array([1, 14, 6])
print(array1, array2)

[2 4 9] [ 1 14  6]


10.1 What is the result of *a + b*?

In [18]:
print(array1 + array2)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [19]:
print(array1 - array2)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [20]:
print(array1 * array2)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [21]:
print(array1 / array2)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [45]:
arr = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [27]:
print(arr[1, 1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [29]:
arr2 =  arr[1:2]
print(arr2)

[[40 50 60]]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [52]:
print(arr[0:3, 2])

[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [54]:
arr3 = np.array(arr[1:3, 1:3]) 
print(arr3)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [58]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [59]:
arr1 = np.array(arr[1:3, 1:3])
print(arr1)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [62]:
arr2 = np.array(arr[0:1, ::2])
print(arr2)

[[1 3]]


4. Write code to reverse the order of rows in the matrix

In [70]:
reversed_row_matrix = arr[::-1]
print(reversed_row_matrix)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [72]:
last_two_coloumns = arr[:, 2:]
print(last_two_coloumns)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [73]:
join_arr1 = np.array([11,7,33])
join_arr2 = np.array([44,5,18])
print(join_arr1, join_arr2)

[11  7 33] [44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [74]:
single1D_arr = np.concatenate((join_arr1, join_arr2))
print(single1D_arr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [75]:
stacked_arr = np.stack((join_arr1, join_arr2), axis=1)
print(stacked_arr)

[[11 44]
 [ 7  5]
 [33 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [77]:
join2D_arr1 = ([[1,2],
               [3,4]])
join2D_arr2 = ([[5,6],
                [7,8]])
print(join2D_arr1)
print(join2D_arr2)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


5. Write code to join them horizontally (column-wise).

In [78]:
hstack = np.hstack((join2D_arr1, join2D_arr2))
print(hstack)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [80]:
vstack = np.vstack((join2D_arr1, join2D_arr2))
print(vstack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [85]:
arrange_1D = np.arange(10,29,2)
print(arrange_1D)

rand_2D = random.randint(50, size=(4,4))
print(rand_2D)

ones_3D = np.ones((2,3,4))
print(ones_3D)



[10 12 14 16 18 20 22 24 26 28]
[[18  6 20 38]
 [12 26 46 20]
 [10 17  9 12]
 [21 35 29 19]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [94]:
reshape_1D = arrange_1D.reshape(2, -1)
print(reshape_1D)

extract_2D = rand_2D[2:4, ::]  
print(extract_2D)

replace_2D = rand_2D[rand_2D % 2 == 0] = -1
print(replace_2D)

[[10 12 14 16 18]
 [20 22 24 26 28]]
[[-1 17  9 -1]
 [21 35 29 19]]
-1


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [99]:

mean = np.mean(rand_2D)
median = np.median(rand_2D)
std = np.std(rand_2D)

print("Mean: ",mean)
print("Median: ",median)
print("Standard Deviation: ",std)


Mean:  7.5
Median:  -1.0
Standard Deviation:  12.114041439585717


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [107]:
arr_10x10 = random.rand(10,10)
print(arr_10x10)

min_values = np.min(arr_10x10, axis=0)

print("\nMinimum values along each column:")
print(min_values)


[[0.92506532 0.75927022 0.58154664 0.1156974  0.2870989  0.990483
  0.32312904 0.40315752 0.79094889 0.84966707]
 [0.75695034 0.12674119 0.82785895 0.67760033 0.72974998 0.95219998
  0.23715135 0.27811618 0.73506839 0.33045258]
 [0.98914862 0.96684691 0.38184141 0.57048581 0.98572548 0.36172727
  0.4312724  0.5047739  0.54240783 0.99901306]
 [0.02575209 0.6665283  0.80931757 0.23010061 0.65537717 0.75582797
  0.27701809 0.85385298 0.59818556 0.88448541]
 [0.42030964 0.98563929 0.36912264 0.16169076 0.99895322 0.09040678
  0.06485402 0.12922743 0.13331106 0.66287871]
 [0.22699855 0.48493752 0.36446175 0.27671649 0.80923948 0.7960907
  0.61763074 0.51699505 0.09768913 0.74093962]
 [0.09237186 0.08333075 0.9480523  0.54708864 0.80545077 0.63164448
  0.32187511 0.5865743  0.75646344 0.56731589]
 [0.88815429 0.87058206 0.42032587 0.23032026 0.41002804 0.22437183
  0.79897741 0.82103639 0.78520753 0.44454416]
 [0.14307324 0.89840999 0.12894538 0.33641271 0.89241243 0.9398575
  0.77834769 0.2